### ISSUE TITLE
Allow customizable subject?

### ISSUE THREAD

**Issue by zalary** [activeprospect/leadconduit-integration-email-delivery#2]
One of the feature requests that came out of the quarterly setup challenge was to be able to edit the subject line for lead email deliveries.

**Comment by cgrayson** [comment]
The "Email Use Cases" Google doc doesn't specify how subject should be set in this case. What do you think, @alexj?

**Comment by alexj** [comment]
Good point Zal, it would make sense to make the subject editable for this integration. Let's make the default: `New Lead from LeadConduit Flow: #{vars.flow.name}`
